### ISSUE TITLE
How to run FIST with your own data?

### ISSUE THREAD

**Issue by carloelle** [kuanglab/FIST#1]
Hi,

I'd like to give a try on FIST using my Visium data. I used Convert2Tensor_Visium.R in order to create the .mat file, then in MATLAB in the FIST_utils I generated the data tensor running `V = sptensor([V.x_aligned_coords V.y_aligned_coords V.variable], V.value, [double(X) double(Y) double(Z)])`. 
At this point, how I can proceed in order to obtain the imputed ST matrix using FIST?
Any quick tutorial would be appreciated!

Thanks,
CL

**Comment by kuanglab** [comment]
We updated the Readme.md file to include a tutorial on how to run the experiment on one Visium dataset. Try it and let us know if there is any question.
